name: run

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        name: [World, Octocat]

    steps:
      - uses: kevinpollet/typescript-container-action-template@master
        with:
          name: ${{matrix.name}}
